version: '3'

services:
  # Servicio de base de datos PostgreSQL para Airflow y staging
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos de Postgres

  # Servicio que inicializa la base de datos de Airflow (solo corre una vez)
  airflow-init:
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor  # Ejecuta tareas localmente
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow  # Conexión a Postgres
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    entrypoint: ["/bin/bash", "-c"]
    command: ["airflow db init"]  # Crea tablas y metadatos de Airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags      # DAGs compartidos
      - ./airflow/logs:/opt/airflow/logs      # Logs persistentes
      - ./airflow/plugins:/opt/airflow/plugins  # Plugins personalizados
      - ./airflow/data:/opt/airflow/data      # Área de staging para CSVs

  # Webserver de Airflow: interfaz web para ver y ejecutar DAGs
  airflow-webserver:
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - airflow-init
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    ports:
      - "8080:8080"  # Exponer UI de Airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    command: webserver  # Iniciar el server web

  # Scheduler: orquesta tareas programadas
  airflow-scheduler:
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - airflow-init
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    command: scheduler  # Ejecutar el scheduler de Airflow

volumes:
  postgres_data:  # Volumen para persistir datos de Postgres
